spring.application.name=sdwan-assignment-starter-api
server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

logging.level.root=INFO
logging.level.com.example.sdwan=DEBUG
